name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [ '1.22' ]
        goos: [ 'linux', 'darwin' ]
        goarch: [ 'amd64', 'arm64' ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Test
      run: go test -v ./...

    - name: Build
      run: |
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o raiden-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Upload binary to release
      uses: actions/upload-artifact@v3
      with:
        name: raiden-${{ matrix.goos }}-${{ matrix.goarch }}
        path: raiden-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: raiden-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
